project:
  type: website

website:
  page-navigation: true
  site-url: "https://openscapes.github.io/quarto-website-tutorial"
  repo-url: "https://github.com/openscapes/quarto-website-tutorial"
  repo-actions: [edit, issue]

  navbar:
    search: true
    left:
      - href: index.qmd
        text: The Story

      - text: The Research
        href: content/Research.qmd

      - text: About Me
        href: content/About.qmd
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Quarto website tutorial"
        

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"

format:
  html:
    theme: cosmic
    css: assets/custom.css
    code-copy: true
    code-overflow: wrap
    toc: false

filters:
  - include-files.lua
  - quarto